# Version Android Allo Tata : X.Y.Z
# Tu changes uniquement major (X) et minor (Y).
# patch (Z) et versionCode sont incrémentés à chaque compilation.

major=1
minor=0
patch=6
versionCode=6
versionName=1.0.6
lastMajor=1
lastMinor=0
